return {
    mod_name = {
        en = "Valkyrie CJK Font Fix",
        ["zh-cn"] = "瓦尔基里 CJK 字体修复",
        ["zh-tw"] = "瓦爾基里 CJK 字體修復",
        ja = "ヴァルキリー CJK フォント修正",
        ko = "발키리 CJK 폰트 수정",
    },
    mod_description = {
        en = "Fixes boxed (tofu) CJK characters on Valkyrie's loading screen business cards by routing non-Latin text through the CJK font fallback chain installed by Show CJK Glyphs +.",
        ["zh-cn"] = "修复瓦尔基里加载界面名片上中文等字符显示为方框的问题：让含非拉丁字符的文本走 Show CJK Glyphs + 提供的 CJK 字体回退链。",
        ["zh-tw"] = "修復瓦爾基里載入界面名片上中文等字元顯示為方框的問題：讓含非拉丁字元的文字走 Show CJK Glyphs + 提供的 CJK 字體回退鏈。",
        ja = "ヴァルキリーのロード画面の名刺でCJK文字が□（豆腐）表示になる問題を修正します。非ラテン文字を含むテキストを Show CJK Glyphs + が提供するCJKフォールバックフォントチェーン経由で描画します。",
        ko = "발키리의 로딩 화면 명함에서 CJK 문자가 네모(토후)로 표시되는 문제를 수정합니다. 비라틴 문자가 포함된 텍스트를 Show CJK Glyphs +가 제공하는 CJK 폴백 폰트 체인으로 렌더링합니다.",
    },
    only_non_latin = {
        en = "Only redirect non-Latin text",
        ["zh-cn"] = "仅重定向非拉丁文字",
        ["zh-tw"] = "僅重新導向非拉丁文字",
        ja = "非ラテン文字のテキストのみ再描画",
        ko = "비라틴 문자 텍스트만 리다이렉트",
    },
    only_non_latin_description = {
        en = "When enabled, only strings containing non-Latin characters are re-rendered with the CJK-capable fallback font; pure ASCII strings keep Valkyrie's original font.",
        ["zh-cn"] = "启用时，仅包含非拉丁字符的文本改用带 CJK 回退的字体绘制；纯 ASCII 文本保持瓦尔基里原有字体。",
        ["zh-tw"] = "啟用時，僅包含非拉丁字元的文字改用帶 CJK 回退的字體繪製；純 ASCII 文字保持瓦爾基里原有字體。",
        ja = "有効時、非ラテン文字を含む文字列のみCJK対応フォールバックフォントで再描画します。純粋なASCII文字列はヴァルキリーの元のフォントのままです。",
        ko = "활성화하면 비라틴 문자가 포함된 문자열만 CJK 지원 폴백 폰트로 다시 렌더링합니다. 순수 ASCII 문자열은 발키리의 원래 폰트를 유지합니다.",
    },
    debug_logging = {
        en = "Debug logging",
        ["zh-cn"] = "调试日志",
        ["zh-tw"] = "除錯紀錄",
        ja = "デバッグログ",
        ko = "디버그 로깅",
    },
    debug_logging_description = {
        en = "Log diagnostic information (locale, resolved fonts, draw results) to the console log. Turn off once the fix is confirmed working.",
        ["zh-cn"] = "向控制台日志输出诊断信息（语言、解析出的字体、绘制结果）。确认修复生效后可关闭。",
        ["zh-tw"] = "向主控台紀錄輸出診斷資訊（語言、解析出的字體、繪製結果）。確認修復生效後可關閉。",
        ja = "診断情報（言語、解決されたフォント、描画結果）をコンソールログに出力します。修正の動作確認後はオフにしてください。",
        ko = "진단 정보(언어, 해석된 폰트, 렌더링 결과)를 콘솔 로그에 출력합니다. 수정 확인 후에는 끄세요.",
    },
    localize_labels = {
        en = "Localize card labels",
        ["zh-cn"] = "本地化卡片标签",
        ["zh-tw"] = "本地化卡片標籤",
        ja = "名刺ラベルをローカライズ",
        ko = "명함 라벨 현지화",
    },
    localize_labels_description = {
        en = "Translate the card texts (labels like Name:/Class:/Special Ability:, and fallback values like None/Unknown) to follow the game's current language.",
        ["zh-cn"] = "将名片文本（名字、职业、特殊能力等标签，以及 None/Unknown 等兜底值）翻译为游戏当前语言。",
        ["zh-tw"] = "將名片文字（名字、職業、特殊能力等標籤，以及 None/Unknown 等兜底值）翻譯為遊戲目前語言。",
        ja = "名刺のテキスト（名前、クラス、特殊能力などのラベルと、None/Unknown などのフォールバック値）をゲームの現在の言語に翻訳します。",
        ko = "명함 텍스트(이름, 직업, 특수 능력 등의 라벨과 None/Unknown 같은 폴백 값)를 게임의 현재 언어로 번역합니다.",
    },
    card_value_none = {
        en = "None",
        fr = "Aucun",
        de = "Keine",
        it = "Nessuno",
        es = "Ninguno",
        pl = "Brak",
        ["pt-br"] = "Nenhum",
        ru = "Нет",
        ja = "なし",
        ko = "없음",
        ["zh-cn"] = "无",
        ["zh-tw"] = "無",
    },
    card_value_unknown = {
        en = "Unknown",
        fr = "Inconnu",
        de = "Unbekannt",
        it = "Sconosciuto",
        es = "Desconocido",
        pl = "Nieznany",
        ["pt-br"] = "Desconhecido",
        ru = "Неизвестно",
        ja = "不明",
        ko = "알 수 없음",
        ["zh-cn"] = "未知",
        ["zh-tw"] = "未知",
    },
    card_label_name = {
        en = "Name:",
        fr = "Nom :",
        de = "Name:",
        it = "Nome:",
        es = "Nombre:",
        pl = "Imię:",
        ["pt-br"] = "Nome:",
        ru = "Имя:",
        ja = "名前：",
        ko = "이름:",
        ["zh-cn"] = "名字：",
        ["zh-tw"] = "名字：",
    },
    card_label_class = {
        en = "Class:",
        fr = "Classe :",
        de = "Klasse:",
        it = "Classe:",
        es = "Clase:",
        pl = "Klasa:",
        ["pt-br"] = "Classe:",
        ru = "Класс:",
        ja = "クラス：",
        ko = "직업:",
        ["zh-cn"] = "职业：",
        ["zh-tw"] = "職業：",
    },
    card_label_special_ability = {
        en = "Special Ability:",
        fr = "Capacité spéciale :",
        de = "Spezialfähigkeit:",
        it = "Abilità speciale:",
        es = "Habilidad especial:",
        pl = "Zdolność specjalna:",
        ["pt-br"] = "Habilidade especial:",
        ru = "Особое умение:",
        ja = "特殊能力：",
        ko = "특수 능력:",
        ["zh-cn"] = "特殊能力：",
        ["zh-tw"] = "特殊能力：",
    },
    card_label_aura = {
        en = "Aura:",
        fr = "Aura :",
        de = "Aura:",
        it = "Aura:",
        es = "Aura:",
        pl = "Aura:",
        ["pt-br"] = "Aura:",
        ru = "Аура:",
        ja = "オーラ：",
        ko = "오라:",
        ["zh-cn"] = "光环：",
        ["zh-tw"] = "光環：",
    },
    card_label_blitz = {
        en = "Blitz:",
        fr = "Blitz :",
        de = "Blitz:",
        it = "Blitz:",
        es = "Blitz:",
        pl = "Błysk:",
        ["pt-br"] = "Blitz:",
        ru = "Блиц:",
        ja = "ブリッツ：",
        ko = "블리츠:",
        ["zh-cn"] = "闪电技能：",
        ["zh-tw"] = "閃電技能：",
    },
    card_label_keystone = {
        en = "Keystone:",
        fr = "Pierre angulaire :",
        de = "Grundstein:",
        it = "Pietra angolare:",
        es = "Piedra angular:",
        pl = "Kamień węgielny:",
        ["pt-br"] = "Pedra angular:",
        ru = "Краеугольный камень:",
        ja = "キーストーン：",
        ko = "핵심석:",
        ["zh-cn"] = "基石：",
        ["zh-tw"] = "基石：",
    },
    card_label_melee = {
        en = "Melee:",
        fr = "Mêlée :",
        de = "Nahkampf:",
        it = "Corpo a corpo:",
        es = "Cuerpo a cuerpo:",
        pl = "Walka wręcz:",
        ["pt-br"] = "Corpo a corpo:",
        ru = "Ближний бой:",
        ja = "近接：",
        ko = "근접:",
        ["zh-cn"] = "近战：",
        ["zh-tw"] = "近戰：",
    },
    card_label_ranged = {
        en = "Ranged:",
        fr = "Distance :",
        de = "Fernkampf:",
        it = "A distanza:",
        es = "A distancia:",
        pl = "Dystans:",
        ["pt-br"] = "À distância:",
        ru = "Дальний бой:",
        ja = "遠距離：",
        ko = "원거리:",
        ["zh-cn"] = "远程：",
        ["zh-tw"] = "遠程：",
    },
}
